jobs:
  include:
  - os: linux
    dist: bionic
language: c++
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda install -c conda-forge mamba
- mamba create -q -n test-environment -c conda-forge -c bioconda -y clang meson samtools gxx_linux-64
- conda activate test-environment
- env CXX=clang meson setup --buildtype=release builddir
- cd builddir
- meson compile
- meson test
script:
- echo "done"
