jobs:
  include:
  - os: linux
    dist: bionic
  - os: osx
language: c++
install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export conda_url=https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
  fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then export conda_url=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
  fi
- wget $conda_url -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export toolchain=clangxx_osx-64; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then export toolchain=gxx_linux-64; fi
- conda install -c conda-forge mamba
- mamba create -q -n test-environment -c conda-forge -c bioconda -y clang=10 meson samtools $toolchain
- conda activate test-environment
- env CXX=clang meson setup --buildtype=release builddir
- cd builddir
- meson compile
- meson test
